Repository hashicorp/terraform-plugin-mux, pull requests merged in 2022-12, with the labels that each got.

#118 Ignore MinItems and MaxItems diff in nested block
  .changelog/118.txt
  tf5muxserver/mux_server_test.go
  tf5muxserver/schema_equality.go
  tf6muxserver/mux_server_test.go
  tf6muxserver/schema_equality.go
  website/docs/plugin/mux/combining-protocol-version-5-providers.mdx
Labels: tf-devex-triage

#120 website: Fix update/downgrade server code examples to include wrapping function
  website/docs/plugin/mux/translating-protocol-version-5-to-6.mdx
  website/docs/plugin/mux/translating-protocol-version-6-to-5.mdx
Labels: documentation

#121 tf5muxserver+tf6muxserver: Defer combined server implementation errors until GetProviderSchema RPC
  .changelog/121.txt
  tf5muxserver/mux_server.go
  tf5muxserver/mux_server_GetProviderSchema.go
  tf5muxserver/mux_server_GetProviderSchema_test.go
  tf5muxserver/mux_server_test.go
  tf6muxserver/mux_server.go
  tf6muxserver/mux_server_GetProviderSchema.go
  tf6muxserver/mux_server_GetProviderSchema_test.go
  tf6muxserver/mux_server_test.go
Labels: bug
